# Generated by Django 5.0.1 on 2024-01-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
